### ISSUE TITLE
does .pipignore work?

### ISSUE THREAD

**Issue by rsyring** [nvie/pip-tools#110]
I have a .pipignore file in the same directory as my requirements files and it has a single line with "ipython" in it.  However, when I run pip-dump, ipython still shows up in the file.

**Comment by nvie** [comment]
`.pipignore` is now gone with the release of 1.0: http://nvie.com/posts/pip-tools-10-released/

**Comment by rsyring** [comment]
The .pipignore file is still referenced in the diagram that is part of the project readme.

**Comment by nvie** [comment]
Thanks, fixed!
