### ISSUE TITLE
Origin of 'split string' in pip-dump has changed

### ISSUE THREAD

**Issue by michaeljones** [nvie/pip-tools#129]
Hi,

pip-dump seems to depend on a particular output string from `pip`:

  https://github.com/nvie/pip-tools/blob/master/bin/pip-dump#L35

Unfortunately, that string has changed from 'pip --freeze' to 'pip freeze' in the `pip` code base:

  https://github.com/pypa/pip/commit/fa5adbc33bcf2e3d0ffdaccce92c37dfcd818183

So I think `pip-dump` needs to be updated. As it is currently a string equality test, I guess it would make sense to switch to a `glob` or `regex` so that we can support both versions of the string.

Happy to submit a patch if you're interested.

Cheers,
Michael

**Comment by nvie** [comment]
Thanks, yes, that'd be appreciated!

**Comment by michaeljones** [comment]
Fixed in #131. All good.
