### ISSUE TITLE
Transient dependencies

### ISSUE THREAD

**Issue by wernight** [nvie/pip-tools#132]
PIP-tools provides really good practice for pinning dependencies, but it makes it harder to CRUD them because real dependencies are mixed together with transient dependencies.

For example is you need Django and South, it'll also require all their dependencies recursively.

It would be better to have all transient dependencies automatically grouped together. Example:

    # [ Auto-Generated by pip-tools ]
    Django==1.6.6
    South==1.0.1

    # Transient dependencies
    six==1.9.0

This could work by:
 * Having pip-dump append sorted to after the last comment
 * Add a command like `pip-add -r dev-requirement.txt Django` which would add `Django` as dependency and transient dependencies like in the format above.

**Comment by nvie** [comment]
You should check out the `future` branch on this repo, which is all about solving this very problem.

**Comment by nvie** [comment]
Additionally, you may check out this blog post: http://nvie.com/posts/better-package-management/
