### ISSUE TITLE
Why no pip-review in the future branch?

### ISSUE THREAD

**Issue by papasax** [nvie/pip-tools#136]
Hi,

I'm testing the pip-compile function in the future branch. It's a good idea and i'd like to use it on my projects instead of pip-dump.
Why did you remove the pip-review tool?

**Comment by nvie** [comment]
It's not necessary anymore. Re-running `pip-compile` will locally modify your `.txt` file, which has the same effect `pip-review` had.

**Comment by jgonggrijp** [comment]
[pip-review is now a separate package on PyPI](https://pypi.python.org/pypi/pip-review).
