### ISSUE TITLE
pip-review --auto broke my pip

### ISSUE THREAD

**Issue by renta** [nvie/pip-tools#143]
When I've made (made with sudo because without it there were an error about cleaning packages):
sudo pip-review --auto

and now I get this error on trying to use "pip" command:

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

My os (Xubuntu) (command "lsb_release -a"):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

**Comment by nvie** [comment]
I don't think pip-tools broke anything. You should have read the original error message and addressed it, whatever it was about. Blindly using `sudo` can cause all kinds of damage and you should avoid it unless there's absolutely no other way and you actually need root access.

I'm sorry to say I have no clue what happened in this particular case, and I'm unable to help you :(

**Comment by renta** [comment]
My issue was because of old packages versions in Ubuntu, I think. Pip was installed with apt. So I've fixed it with:

sudo apt-get purge python-pip # remove an old "apt" version
easy_install -U pip # install it with python setuptools
hash -r # current user can use "pip" command

Now my pip is OK.

Worth reading:

http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread
https://askubuntu.com/questions/561377/pip-wont-run-throws-errors-instead
https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991
http://stackoverflow.com/questions/16237490/i-screwed-up-the-system-version-of-python-pip-on-ubuntu-12-10

**Comment by nvie** [comment]
Good to hear you have recovered. I would recommend not using the system Python version ever and instead use a virtualenv that is owned by a non-root user, and never use `sudo` to install a Python package.

**Comment by blueyed** [comment]
I can recommend pyenv.

**Comment by renta** [comment]
@nvie , @blueyed I use virtualenvwrapper for my python projects. I wonder, what startegy of updating packages would be the best:

- mass-updating all the packages in pip with something like "pip-review --auto" like I do in apt, for example.

Or

- manuaily updating package-by-package to check if there is a confclict after the update. Because  after this crash I suppose that pip could not guarantee the safe update.
