### ISSUE TITLE
Feature Request: dump only requirements listed in requirements files

### ISSUE THREAD

**Issue by kevgathuku** [nvie/pip-tools#151]
I would like to put forward a feature request:
As the `pip-dump` command currently exists, it also dumps requirements that are installed but are not listed in the requirements files to the first file among the requirements files.
Would it be possible to have a flag that can enable/disable dumping only the requirements listed in the requirements files?
i.e. only the requirements listed in a particular file will be dumped to that file.
and requirements that are installed but not listed in any file will be ignored.
To use this in the current version, I am currently commenting out this line https://github.com/nvie/pip-tools/blob/master/bin/pip-dump#L130

**Comment by nvie** [comment]
This use case is exactly what the `pip-compile` script on the future branch is all about. I'm getting closer to a 1.0 release, which will remove pip-dump and replace it with pip-compile. I'm not going to patch pip-dump (aka the master branch, aka any 0.* release) anymore in favor of the new tool suite.

**Comment by kevgathuku** [comment]
Okay. Thanks for taking the time to reply.
Let me try it out.
