### ISSUE TITLE
pip-compile does not handle extra requirements

### ISSUE THREAD

**Issue by lseek** [nvie/pip-tools#154]
I have a requirements.in file with an "extra" requirement:
```
foopkg[FEATURE1]
```

When I `pip-compile` this requirement file what I get is:
```
foopkg==X.Y
```

What I would expect is:
```
foopkg==X.Y [FEATURE1]
```

In other words, `FEATURE1` and its requirements are missing and therefore doesn't get installed when I `pip install -r requirements.txt`.

Is there any way to work around this at the moment?

**Comment by nvie** [comment]
Hi @lseek, thank for this. I'll have a look into what it takes to support this. I've personally never used them, but pip-compile should definitely support these use cases too. It may have a bit of an impact on the internals, but I'll have a look and see if I can add this.

**Comment by nvie** [comment]
Do you have an example of a package that uses extras, so I can look into this?

**Comment by piotr-dobrogost** [comment]
For instance requests library uses them – https://github.com/kennethreitz/requests/blob/master/setup.py#L71

**Comment by nvie** [comment]
I'm going to work on this as far as time permits me. I've added a message that this is not yet supported in the meantime.

**Comment by hale** [comment]
I ran into this when including `ipython` in `requirements.in`.

So, that's an example of a package that uses extras.  

(The [install docs](http://ipython.org/ipython-doc/dev/install/install.html) say to install like `ipython[all]`)

**Comment by gavinwahl** [comment]
Is this expected to be difficult to implement? I might be able to do it with some guidance.

**Comment by paulkernfeld** [comment]
I added a pull request, #202, that adds support for extras in pip-compile. Please let me know what I need to do to get this merged in!

**Comment by paulkernfeld** [comment]
Pull request #202 is merged now, so this issue can be closed.

**Comment by coriolinus** [comment]
I'm encountering this right now.

Sample from requirements.in:
```
pip-tools               # needed for pip-compile and pip-sync
hypothesis[django]      # testing framework
```

Sample from requirements.txt:

```
hypothesis==3.6.0
pip-tools==1.7.0
```

**Comment by paulkernfeld** [comment]
@coriolinus can you open a new issue for this, please? In the new issue, can you describe what you are expecting to happen, compared with what is actually happening? Are you seeing an error, for example? If you tag me on the new ticket I can take a look.

**Comment by coriolinus** [comment]
@paulkernfeld No problem; I created the issue last night but forgot to mention you then. Either way, it's up now: #408 .
