### ISSUE TITLE
future: does not handle VCS URLs properly anymore

### ISSUE THREAD

**Issue by blueyed** [nvie/pip-tools#155]
% echo 'git+https://github.com/nvie/pip-tools.git@future#egg=pip-tools' > test.in
    % pip install 'git+https://github.com/nvie/pip-tools.git@future#egg=pip-tools'
    % pip-compile test.in                                                            
    #
    # This file is autogenerated by pip-compile
    # Make changes in test.in, then run this to update:
    #
    #    pip-compile test.in
    #
    pip-tools==0.3.6

It should not use 0.3.6, but use the VCS URL.

`pip freeze` itself says `pip-tools==1.0.dev1`.

**Comment by blueyed** [comment]
A workaround is to use `-e` with them, but then they are not getting pinned to the current commit, like it used to be:

    -e git+https://github.com/nvie/pip-tools.git@future#egg=pip-tools

**Comment by nvie** [comment]
Agreed, this is unanticipated behaviour. The `pip-tools==0.3.6` output is plain wrong. The exact semantics here are unclear to me. I do consider it a bug if this behaviour differs from pip. To avoid stepping into the pitfall again of supporting all edge cases, I'm happy to block the particular use case of adding direct links, whether they are "normal" links or VCS urls—in essence, it requires downloading the package and installing it.

If we can support this by using pip internals, great. Until then, I'll go for a patch that detects this use case (InstallRequirement has a link, but is not editable?), and emits an error that this is not supported.

**Comment by blueyed** [comment]
The previous format was:

    git+git://github.com/bfirsh/django-ordered-model@9895bb4b31742274c1906065b2f339344f1f7fb8#egg=django-ordered-model

I am using Git links in cases where I have a fork of a project with some additional changes or if a package (update) has not been released yet.

I don't know if this can be done with pip functions.

The workaround is using `-e`, which is OK for me at the moment - and should not get blocked / cause an error.

**Comment by nvie** [comment]
I've added a message that this is not supported, so it fails explicitly, instead of doing the wrong thing. The error message now suggests using the `-e` option.

**Comment by blueyed** [comment]
I've created a followup issue for pinning Vcs dependencies: #161.

The current behaviour of not pinning those anymore (to a specific commit) is bad and defeats the purpose of pip-compile (for Vcs packages)..
