### ISSUE TITLE
Add `--no-upgrade` flag to `pip-compile`

### ISSUE THREAD

**Issue by nvie** [nvie/pip-tools#166]
This should prevent executing version updates, but shoud add/remove dependencies as they have (dis)appeared in *.in files. This would be useful to add a new dependency to in *.in file, and have `pip-compile` only resolve that new package and add it to the *.txt file.

There are a lot of edge cases though, so getting the semantics right here is non-trivial.

**Comment by jgonggrijp** [comment]
I'm glad this was tackled, it greatly improves interoperability with pip-review because it separates updating from pinning.
