### ISSUE TITLE
choosing between pip2 and pip3

### ISSUE THREAD

**Issue by smason** [nvie/pip-tools#172]
Is there a nice way to choose between reviewing package states for python 2/3?  I currently hack the source to switch between calling out to pip2 and pip3.

Maybe allowing multiple versions to coexist like pip does? I'd then be able to run `pip3-review` and `pip2-review` and have it see the "correct" packages.

**Comment by svetlyak40wt** [comment]
Use separate virtualenvs for python2 and python3

**Comment by smason** [comment]
I've been putting off learning `virtualenv` for too long, looks like it's time to take the plunge…

**Comment by svetlyak40wt** [comment]
@smason Sam, virtualenv is must have for python devlopment. I'm wincing remembering days when virtualenv didn't exist.

**Comment by smason** [comment]
Alexander Artemenko wrote:
> @smason Sam, virtualenv is must have for python devlopment. I'm
> wincing remembering days when virtualenv didn't exis

Package/version dependencies haven't been much of an issue for
me—but then again, I've generally stuck with Python's standard
library…

  Sam
