### ISSUE TITLE
pip-compile: optionally do not resolve includes ("-r")

### ISSUE THREAD

**Issue by blueyed** [nvie/pip-tools#174]
To speed up compiling requirements, it would be useful if `pip-compile` would not resolve includes.

With e.g. `-r base.txt` in `dev.in`, `base.in` needs to be compiled only once to `base.txt`, and the `-r base.txt` could be kept as-is (instead of being resolved inline).

The following could be used to manually achieve this currently (in a Makefile):

    $(PIP_REQUIREMENTS_DIR)/%.txt: $(PIP_REQUIREMENTS_DIR)/%.in
	in=$$(mktemp -p $(PIP_REQUIREMENTS_DIR) -t req.XXXXXX.$(notdir $<)) \
	  && test -f $$in \
	  && { \
	    req_includes=$$(grep -E '^-r.*\.txt' $<); \
	    grep -E -v '^({%|-r.*\.txt)' $< > $$in; \
	    printf -- '# This file is autogenerated by pip-compile.\n\n' > $@; \
	    if [ -n "$$req_includes" ]; then printf -- "$$req_includes\n\n" >> $@; fi; \
	    pip-compile --no-header --dry-run $$in | grep -v '# via' >> $@; \
	    rm $$in; }

**Comment by lsmag** [comment]
This is also useful when I have multiple requirements including base.txt (`development.txt,test.txt,production.txt`). Right now when I change base.txt I must regenerate all dependant files.

**Comment by pmdarrow** [comment]
@nvie is there any interest in a PR for this?

**Comment by nvie** [comment]
Since speed is the main goal here, I don't think we should add this to pip-tools. I want to keep it light, and try to keep support for edge cases minimal. This issue was opened Jun 2015, I assume that was still in the pip 6 days. Pip itself has seen massive speed-ups during that time, and pip-compile has gotten way faster as a direct result of that, so I'm not sure if this is still a valid argument. I'm closing this issue now.

**Comment by blueyed** [comment]
@nvie 
Speed is not the main issue here, but clarity: if you bump your requirements, it's much clearer if it only gets changed in `base.txt`, and not also in `prod.txt`, `base.txt` etc.

I am currently using the following, which somehow works around it, but dependencies will be also added to dev.txt, although they are in base.txt already.
Luckily this is only a problem if the versions differ (e.g. because dev.txt was updated, but base.txt was not): 

> Double requirement given: pytest==2.9.2 (from -r requirements/dev.txt (line 28)) (already in pytest==2.9.1 (from -r requirements/travis.txt (line 11)), name='pytest')

This Makefile snippet replaces some custom "Depends on" comment with "-r", after running pip-compile.

```make
$(PIP_REQUIREMENTS_DIR)/%.txt: $(PIP_REQUIREMENTS_DIR)/%.in
	pip-compile --no-header --output-file "$@.tmp" "$<" >/tmp/pip-compile.out.tmp || { \
	  ret=$$?; echo "pip-compile failed:" >&2; cat /tmp/pip-compile.out.tmp >&2; \
	  $(RM) "$@.tmp" /tmp/pip-compile.out.tmp; \
	  exit $$ret; }
	@sed -n '1,10 s/# Depends on/-r/; s/\.in/.txt/p' "$<" > "$@"
	@cat "$@.tmp" >> "$@"
	@$(RM) "$@.tmp" /tmp/pip-compile.out.tmp
```

And improved speed is a nice side effect of this, too - of course.

So, please consider re-opening this issue.
