### ISSUE TITLE
pip-review chokes on -f

### ISSUE THREAD

**Issue by eli-collins** [nvie/pip-tools#175]
`pip-review` currently throws an error on line 154 when it encounters a "-f ..." line in the output of `pip freeze`. I think modifying line 144 of `pip-review`...

> if not line or line.startswith('##'):

... to read instead ...

> if not line or line.startswith(('##', "-f")):

would fix things; but not sure if there was a better place / if "-f" lines should be handled differently.

**Comment by nvie** [comment]
`pip-review` is gone with the release of 1.0: http://nvie.com/posts/pip-tools-10-released/

**Comment by jgonggrijp** [comment]
@eli-collins [pip-review](https://pypi.python.org/pypi/pip-review) can now be installed separately from PyPI. Please resubmit your issue to the [pip-review issue tracker](https://github.com/jgonggrijp/pip-review/issues) if you feel it is still relevant.
