### ISSUE TITLE
pip-compile no longer respects extra-index-url

### ISSUE THREAD

**Issue by beeftornado** [nvie/pip-tools#180]
pip-compile used to retain --extra-index-url in the requirements.in file, but now it always replaces it with its own regardless of what I supply.

Additionally, if I supply one on the command line, it also doesn't carry over to the generated file. It adds a new extra-index-url but not with the value I specified. It always uses the default pypi.python.org

Example
```
# requirements.in
raven==5.4.1
--extra-index-url https://pypi.internal.mycompany.com/simple

# output of `pip-compile`
--extra-index-url https://pypi.python.org/simple/
raven==5.4.1

# output of `pip-compile --extra-index-url https://pypi.internal.mycompany.com/simple requirements.in`
--extra-index-url https://pypi.python.org/simple/
--extra-index-url https://pypi.python.org/simple/
raven==5.4.1
```

**Comment by nvie** [comment]
Thanks for catching this one! Fixed in e964f3f92b96d58a6666198a57221e231620981b.
