### ISSUE TITLE
pip-sync ignores dev-requirements

### ISSUE THREAD

**Issue by Koed00** [nvie/pip-tools#183]
I'm really happy this got released. Congratulations.

First thing I noticed is that pip-sync will also uninstall the dependencies in dev-requirements.txt which I created with pip-compile from dev-requirements.in

**Comment by Koed00** [comment]
This is a somewhat bigger problem; pip-tools is pinned in my dev-requirements.txt and not in requirements.txt. Therefore pip-sync will actually uninstall pip-tools own requirements like `click` and `first`.

**Comment by hugopeixoto** [comment]
You could add a line to dev-requirements.in with `-r requirements.txt` and run the following:
    pip-compile requirements.in
    pip-compile dev-requirements.in
    pip-sync dev-requirements.txt


One could change pip-sync to accept a list of requirements file instead of just one file, which would make it possible for you to run `pip-sync *requirements.txt`, but then pip-sync would have to have a mechanism of detecting inconsistencies between files.

**Comment by grigi** [comment]
I don't see how the -r is less likely to cause inconsistencies than importing many files.
It feels very natural that it should accept a list of requirements files. I consider it important for usability.

**Comment by nvie** [comment]
I agree pip-sync should be able to handle a list of file inputs. When inconsistencies are detected, we can do any of these:

1. Behaviour is undefined when inconsistencies are found
2. Refuse to sync until inconsistencies are resolved (and report the inconsistency)

I'm for option 2 here, possibly with a `--force` option to ignore conflicts and falling back on 1?

**Comment by nvie** [comment]
I do agree with @Koed00 the issue that pip-tools will uninstall itself (or its dependencies) is a more immediate issue that should be tackled first.

**Comment by hugopeixoto** [comment]
Regarding the uninstallation of self:

`sync.EXCEPTIONS` already includes `pip-tools`, which solves half of the problem.
Here are a couple of ideas on how to handle dependencies (some of them are unfeasible, but I'm listing them anyway):

1. Remove all dependencies from pip-tools (probably not a good idea)
2. Vendor all the dependencies ([which is something pip does](https://github.com/pypa/pip/blob/master/pip/_vendor/__init__.py))
3. Hardcode all dependencies in `sync.EXCEPTIONS` (might become cumbersome to maintain)
4. Create the dependency tree at runtime for all installed exceptions based on the current set of installed modules, and whitelist them

Both (2) and (4) are solutions that seem feasible, but (4) is probably the way to go.

**Comment by hugopeixoto** [comment]
@Koed00 and @grigi, could you try out the PR and see if it works for your cases?

**Comment by Koed00** [comment]
``pip-sync requirements.txt dev-requirements.txt`` works great. It neatly cleans up my env. This has already saved me over 10% in instance sizes btw.

``pip-sync`` with no arguments just uninstalls everything except pip-tools and its requirements.
Maybe it should default to looking for `requirements.txt` at the least.

**Comment by hugopeixoto** [comment]
You're right. It seems that when I specify `nargs=-1`, click ignores the default value. Either I'm doing it wrong, or it may be a bug.

If anyone can spot anything that I'm doing wrong there, let me know.
Meanwhile, I added an extra check, manually checking for no arguments.

**Comment by nvie** [comment]
Thanks, I fixed this one in pip-tools==1.1.1, see 74d175770e76c64141ec37935373ec09a068bb94.
