### ISSUE TITLE
pip-sync will always re-install pip-tools if in requirements file

### ISSUE THREAD

**Issue by grigi** [nvie/pip-tools#188]
Hi, I have pip-tools already installed, and now want to use pip-sync, I always get this:

```
$ pip-sync --dry-run requirements.txt 
Would install:
  pip-tools==1.0.5
```
But pip-tools==1.0.5 is already installed.

I suspect it has something to do with the white listing to never uninstall pip-tools itself.

**Comment by nvie** [comment]
This should be fixed in [pip-tools==1.1.0](https://pypi.python.org/pypi/pip-tools). Thanks for reporting!

**Comment by grigi** [comment]
Hi @nvie 
Unfortunately pip-tools==1.1.1 doesn't resolve this.

Minimal test case (works in both py2.7 and py3.4)(pip==7.1.0 used):
create & activate empty virtualenv:
$ echo pip-tools > requirements.in
$ pip install pip-tools
$ pip-compile
```
#
# This file is autogenerated by pip-compile
# Make changes in requirements.in, then run this to update:
#
#    pip-compile requirements.in
#
click==4.1                # via pip-tools
first==2.0.1              # via pip-tools
pip-tools==1.1.1
six==1.9.0                # via pip-tools
```
$ pip-sync
```
Requirement already satisfied (use --upgrade to upgrade): six==1.9.0 in ./lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): click==4.1 in ./lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): first==2.0.1 in ./lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip-tools==1.1.1 in ./lib/python2.7/site-packages
```

**Comment by nvie** [comment]
Can you try 1.1.2? :)

**Comment by grigi** [comment]
@nvie It works :+1: 
Thanks for such a great tool :-)
