### ISSUE TITLE
question: Does pip-compile put packages it downloads into the download cache for pip install?

### ISSUE THREAD

**Issue by stefanfoulis** [nvie/pip-tools#193]
So that packages that ``pip-compile`` already had to download, don't need to be re-downloaded when ``pip install -r requirements.txt`` (or ``pip-sync ..``) is called.

For this to work well, I guess pip-compile would also have to know if wheels are preferred.

**Comment by Chive** [comment]
I found this:

```bash
root@9edd2e5e9f0c:~# dir -R ~/.cache/pip-tools/
/root/.cache/pip-tools/:
depcache-py2.7.json  pkgs  wheels

/root/.cache/pip-tools/pkgs:
tabulate-0.7.5.tar.gz

/root/.cache/pip-tools/wheels:
aldryn_client-2.0-py2-none-any.whl  requests-2.7.0-py2.py3-none-any.whl
```

**Comment by stefanfoulis** [comment]
thanks for the answer @Chive :-)

**Comment by Chive** [comment]
Actually, I was wrong @stefanfoulis https://github.com/nvie/pip-tools/blob/master/piptools/locations.py#L8

On Linux, it might be ``~/.cache``, but on OS X (at least for me) it's ``/Users/<username>/Library/Caches/pip-tools``
