### ISSUE TITLE
Upgrade boltons.fileutils.AtomicSaver

### ISSUE THREAD

**Issue by mahmoud** [nvie/pip-tools#197]
Hi there! I noticed that you were using the [boltons](https://github.com/mahmoud/boltons) atomic file saving feature. I just wanted to let you know that there have been some recent improvements to cross-platform functionality and corner-case behavior and that you might want to re-vendor the code. There are a couple API improvements, but nothing that would affect your code; it should be 100% drop-in.

Let me know if you have any questions! Thanks for using boltons!

**Comment by nvie** [comment]
Thanks @mahmoud, I did upgrade this back when you reported in August, but I forgot to thank you for it and close this ticket :)

Btw, do you have any idea if this should be fixed in AtomicSaver? I think it'd be a nice little corner case to fix generically: #268

**Comment by mahmoud** [comment]
Agreed! The older version could have done a better job, and I think the current design does a better job than I had originally hoped. I replied over on the other thread; I was unable to reproduce that issue, so I'm hoping it's just a matter of environment or permissions getting copied over from an existing file.
