### ISSUE TITLE
Unicode_literals __future__ import warning

### ISSUE THREAD

**Issue by ajkeys** [nvie/pip-tools#198]
This is fairly low priority, but anytime I run any of the pip-tools I get the below warning. 

```
python2.7/site-packages/piptools/scripts/sync.py:28: Warning: Click detected the use of the unicode_literals __future__ import. 
This is heavily discouraged because it can introduce subtle bugs in your code. 
You should instead use explicit u"" literals for your unicode strings. 
For more information see http://click.pocoo.org/python3/
  @click.argument('src_files', required=False, type=click.Path(exists=True), nargs=-1)
```

Not a big deal, but an annoyance. :) I'm running python 2.7.10, click 5.1 and pip-tools 1.1.3. Looks like click started throwing this warning starting with 5.0. http://click.pocoo.org/5/python3/#unicode-literals mentions two solutions one if you want to listen to the suggestion and another if you want to ignore it.

Thanks!

**Comment by nvie** [comment]
Yeah, it's super annoying. I've just pushed a fix for this to PyPI (pip-tools==1.1.4). Sorry about the delay here.
