### ISSUE TITLE
pip-sync does not respect venvs.

### ISSUE THREAD

**Issue by jaccarmac** [nvie/pip-tools#203]
I have installed pip-tools globally. When trying to run pip-sync inside a venv, it uninstalls and installs packages globally instead of in the active venv. The bug happens with both pyvenv and virtualenv and both with and without `--system-site-packages`.

Using Python 3.5 (from source) on Ubuntu 15.10 and ZSH. Most recent stable setuptools, pip, and pip-tools.

**Comment by shimon** [comment]
@jaccarmac have you tried simply installing pip-tools within the virtualenv? This works for me.

**Comment by jaccarmac** [comment]
That works.

However, the documentation seems to indicate that `pip-sync` respects boundaries and that both `pip-compile` and `pip-sync` are global-type commands as opposed to the kind you install in every virtualenv. The picture near the top of the README is misleading as well.

**Comment by houjunchen** [comment]
I got this problem too.

I thought `pip-tools` will be used in every project so I installed it globally. And then `pip-sync` remove all my global packages and install project packages in both global and virtual environments. Maybe this should be highlighted in README.

**Comment by shpsec-oscar** [comment]
I just ran into this as well.  pip-sync in particular is dangerous in a global context, would be great if it would detect wether it is being run with an active virtualenv and fail if it is not.  Perhaps a --force flag if anyone has a valid use case for pip-sync in a global context.

**Comment by taion** [comment]
:+1:

I was unpleasantly surprised when I ran `pip-sync` with a global `pip-tools` install.

**Comment by nvie** [comment]
This should be fixed as a side-effect of the pip-tools==1.4.1 release I just pushed to PyPI. Let me know if this is still a problem!
