### ISSUE TITLE
python 2.7 TypeError: environment can only contain strings

### ISSUE THREAD

**Issue by davidovich** [nvie/pip-tools#209]
I have this error on python 2.7 on Windows when at the resolve cycle.

The resolver.py module sets its unicode literals from the \_\_future\_\_ import, and also wants to inject PIP_EXISTS_ACTION in the os.environ which does not accept unicode data as keys, nor values.

This makes subprocess calls issued in pip fail, because os.environ cannot contain unicode data.

Other projects have had this problem:

https://github.com/mitsuhiko/werkzeug/issues/467
and
https://github.com/celery/django-celery/issues/344

[Other technique seen also on stackoverflow.](http://stackoverflow.com/questions/31003437/python-2-3-os-environ-and-unicode)

One suggestion is to remove the unicode_literals \_\_future\_\_ import and this seems the easiest fix as it supports both python 2.7 and 3.

**Comment by davidovich** [comment]
As of 1.4 this is fixed and verified.
see https://github.com/nvie/pip-tools/commit/3a439045c71851151c51953b79f5994d3a12d9fe
@nvie this issue can be closed.

**Comment by nvie** [comment]
:+1:

**Comment by ibobak** [comment]
This is how I fixed this problem with jupyter kernel http://ihorbobak.com/index.php/2017/12/13/pyspark-kernel-for-jupyter-in-python-2-7-windows/  but I do believe yours can be fixed the same way
