### ISSUE TITLE
pip-compile uses same version for dependency as it does for the parent

### ISSUE THREAD

**Issue by rleonhardt** [nvie/pip-tools#217]
lockfile has been upgraded from 0.10.2 to 0.11.0, which added a new dependency to pbr, which itself has been upgraded from 1.8.0 to 1.8.1.
When I pip-compile a file containing just
```
lockfile
```
the output should be
```
#
# This file is autogenerated by pip-compile
# Make changes in lockfile.in, then run this to update:
#
#    pip-compile lockfile.in
#
lockfile==0.11.0
pbr==1.8.1               # via lockfile

# The following packages are commented out because they are
# considered to be unsafe in a requirements file:
# pip==7.1.2                # via pbr
```
but instead it's
```
#
# This file is autogenerated by pip-compile
# Make changes in lockfile.in, then run this to update:
#
#    pip-compile lockfile.in
#
lockfile==0.11.0
pbr==0.11.0               # via lockfile

# The following packages are commented out because they are
# considered to be unsafe in a requirements file:
# pip==7.1.2                # via pbr
```
Please note the wrong pbr version **0.11.0** (same as current lockfile) instead of the current pbr **1.8.1**.

Strange, when I do `pip install pbr`, pbr-1.8.1-py2.py3-none-any.whl is printed, but `pip list` shows **pbr (0.11.0)**.
When I `pip install pbr==1.8.1`, the correct version is shown in `pip list`.
Maybe there is something wrong with the new pbr version in the pypi database...

**Comment by jonafato** [comment]
This seems like correct behavior and just a coincidence that the versions match. I don't encounter similarly incorrect behavior when installing other packages.

Based on the source (from the tar gzip on [lockfile's PyPI page](https://pypi.python.org/pypi/lockfile)), lockfile is using [pbr](http://docs.openstack.org/developer/pbr/) to manage dependencies. [This feature](http://docs.openstack.org/developer/pbr/#requirements) of pbr reads requirements from requirements.txt files to populate `setup`'s `install_requires` attribute. lockfile provides a requirements.txt file specifying `pbr>=0.6,!=0.7,<1.0` as a requirement. It seems that `pbr==0.11.0` satisfies this version constraint and only coincidentally matches the version of lockfile being installed.

**Comment by rleonhardt** [comment]
Oh, I didn't see the old <1.0 requirement, ```pbr==0.11.0``` really is the last version before 1.0!
Sorry for bothering you, thank you for this great tool, keep up the good work!

**Comment by jonafato** [comment]
@rleonhardt I'm just a user, not the author, but happy to help!
