### ISSUE TITLE
Check packages against vulnerabilities database

### ISSUE THREAD

**Issue by 31z4** [nvie/pip-tools#231]
If you pin your packages versions it's essential to be aware of their vulnerabilities. I think it would be great to have an option for `pip-compile` to check your packages against some vulnerabilities database(s). For example see https://github.com/victims/victims-cve-db.

**Comment by nvie** [comment]
Oh, this could actually be a powerful feature. Who curates that DB? How is it kept up to date?

**Comment by 31z4** [comment]
@nvie I actually don't know. I've just found it here, on github. I wonder if there are better vulnerability databases containing information about Python packages. I also found https://github.com/evilchili/pypi-cve-scanner

**Comment by nvie** [comment]
I like the idea, but perhaps this should not belong in pip-tools, it'll be hard to support / keep up to date. That said, I would totally like to have a tool/script I could run that just checks the contents of requirements.txt against this DB and report which packages are recommended to be updated. Then use pip-tools to record/perform the update.
