### ISSUE TITLE
pip-compile output file ending

### ISSUE THREAD

**Issue by rm--** [nvie/pip-tools#266]
The service [requires.io](https://requires.io/) looking for requirements files ending with `.txt` and `.pip`.
```
Requires.io looks for dependencies in the files matching:

setup.py,
req*.txt or req*.pip,
requirements/*.txt or requirements/*.pip.
```

We liked that idea because it is more clear.
Files ending with `.pip` are related to the `pip command` and it is possible to distinguish them from other `.txt` files. Another argument would be to have a `more explicit` file ending. 
So we changed all our requirements files in [our cookiecutter-template](https://github.com/transcode-de/cookiecutter-django-project) to the ending `.pip`.

With `pip-compile` it is only possible to produce `.txt` requirements files. So we are not able to use both approaches.

Our suggestion would be to add a `command line option` to configure the `file extension for the output format` of `pip-compile`.
The default file extension would be further `.txt` and if someone would like to change the ending it would be possible.

What do you think?

**Comment by nvie** [comment]
I'd add an `--output-file` (`-o`), defaulting to the autogenerated file name. This will be a little more generic. Happy to merge if someone can provide a patch.

**Comment by nvie** [comment]
Seems that #265 may already support this. Will review shortly.

**Comment by rm--** [comment]
What luck. Thanks for the fast reaction! The new version works as expected.
