### ISSUE TITLE
-e relative paths made absolute

### ISSUE THREAD

**Issue by ryanhiebert** [nvie/pip-tools#280]
In my particular case, I have the line `-e .` in my `requirements.in` file. When this is compiled with `pip-compile`, it transforms that line to the full path of the current directory, like `-e /Users/ryanhiebert/Code/python/my-project`. Unfortunately, that's not the correct directory for my production servers, so I have to go back into the generated `requirements.txt` file and change it back to `-e .`, which is quite annoying.

Can we make it so that `-e` lines are kept verbatim, or would that cause problems that I've not thought about?

**Comment by ryanhiebert** [comment]
Oops. Looks like I missed an existing issue about this: #204

**Comment by atugushev** [comment]
The known workaround is `-e file:.#egg=myproject `. See https://github.com/jazzband/pip-tools/issues/204#issuecomment-550051424.
