### ISSUE TITLE
Release 1.4.3 breaks --pip-index-url with a wheel

### ISSUE THREAD

**Issue by pquentin** [nvie/pip-tools#287]
I'm not sure what is relevant in my explanation since I did not investigate yet. Here are the facts:

 * We use devpi to store our Python packages.
 * devpi syncs with PyPI in order to cache all public packages. We need to manually send wheels to devpi however, using `pip wheel` and `devpi upload --formats bdist_wheel wheelhouse/PATH_TO_WHEEL.whl`.
 * To tell pip and pip-compile that it needs to use devpi, we set `PIP_INDEX_URL`, which is recognized just as --index-url (we sent https://github.com/nvie/pip-tools/pull/186 about this last year).
 * The 1.4.3 release is about --index-url and pip-compile 1.4.3 fails to find the matplotlib wheel in devpi. 1.4.2 works.

**Comment by nvie** [comment]
I think this is the only related change between those minor versions: https://github.com/nvie/pip-tools/pull/283/files. Any idea what may be causing this?

**Comment by pquentin** [comment]
Thanks for the pointer. However, our issue is about with pip-compile, not pip-sync, so I don't think this could be the issue?

**Comment by pquentin** [comment]
It's also possible that something else changed when we switched versions. If we continue to get hit by this, I'll try to make sure the issue is reproducible.

**Comment by nvie** [comment]
Is this still an issue after upgrading to 1.6.1?

**Comment by pquentin** [comment]
Sorry @nvie I thought I had closed the issue, because I can't reproduce this anymore. I'll reopen if needed. It does work with pip-tools 1.6. (1.6.1 does not appear to exist yet.)
