### ISSUE TITLE
1.41, 1.42, and 14.3 install packages using system pip rather than virtualenv pip

### ISSUE THREAD

**Issue by jgoettsch** [nvie/pip-tools#288]
The correct packages to install and uninstall are calculated based on what is installed in the virtualenv, but then the installation occurs in the system pip. 1.4.0 and earlier behave correctly.

This is on a CentOS 6 machine using the [Software Collections Repository's Python 2.7](https://wiki.centos.org/AdditionalResources/Repositories/SCL); the system Python is 2.6.

pip-sync is invoked as

```
$ sudo scl enable python27 '/usr/local/envs/foo/bin/pip-sync requirements.txt'
```

The installed packages end up in

```
/usr/lib/python2.6/site-packages
```

**Comment by nvie** [comment]
Yes, this has been deliberately changed. The previous behaviour was consider a bug by many. The `pip-sync` behaviour right now is that it will simply invoke `pip`, leading to whichever pip happens to be on the PATH first. You can inspect for yourself which version that is by running:

   $ which pip

That will likely point to `/usr/bin/pip` in your case.

**Comment by jgoettsch** [comment]
So that requires the virtualenv be activated first:

```
$ source /usr/local/envs/foo/bin/activate
```

Thanks. Please close.

**Comment by nvie** [comment]
Glad that fixed it!
