### ISSUE TITLE
pip-compile unstable on mixed-case dependencies; omits comments

### ISSUE THREAD

**Issue by jbaum-cmcrc** [nvie/pip-tools#311]
Sometimes, pip-compile is unstable as to how a dependency should be spelled from run to run, causing spurious diffs of the form:

    -pyexecjs==1.1.0           # via coffeescript, our_internal_package
    +PyExecJS==1.1.0

Note that in the latter case, the comment is omitted (even though --annotate is specified).

Expected behaviour:
* Dependencies are always spelled the same way (either always mixed-case, or all always lower-case), so that immediately sequential runs of pip-compile result in byte-identical files. This facilitates the recommended usage of checking the resulting file into version control.
* The --annotate option includes comments on all lines.

Version: pip-tools==1.5

**Comment by nvie** [comment]
There recently (since pip 8) popped up this bug: #313, sounds like they're the same. I'm closing this now, since this bug has been addressed and is part of the pip-tools 1.6 release of earlier this morning. Let me know if that fixes it for you. If not, reopen this issue so we can investigate.
