### ISSUE TITLE
pip-review doesn't see 0.10.x when 0.10.0 is installed

### ISSUE THREAD

**Issue by kengruven** [nvie/pip-tools#319]
I've got mongoengine==0.10.0 in my requirements.in / requirements.txt, and it's what's installed right now.  With pip-tools 1.6, when I run "pip-review", it doesn't see that mongoengine==0.10.6 is available on PyPI.

My first thought was that it might consider 0.x to be pre-release, but other 0.x libraries are found by pip-review, and running "pip-review --pre" doesn't find the newer mongoengine, either.

My second thought was that it might be because of the 0.10 (which is a semantic version, not a decimal number), but other library upgrades (like six==1.10.0) were identified by pip-review.

Am I missing something?  Is there any reason this mongoengine upgrade shouldn't be found by pip-review?

**Comment by nvie** [comment]
The script pip-review does not exist with pip-tools 1.6 anymore. It's been removed since 1.x. It is replaced by pip-compile and pip-sync since then. Are you perhaps using a 0.x version of pip-tools?

**Comment by kengruven** [comment]
Strange.  I definitely have pip-tools 1.6 here in my virtualenv, but I also have pip-compile, too.  I guess I have an old version of pip-tools, and upgrading doesn't remove it?

I found [this post](http://nvie.com/posts/pip-tools-10-released/) but I'm a little confused.  Is the pip-review functionality simply gone?  I guess this isn't a bug, then, but I thought that pip-review was incredibly useful, and I'm sorry to see it gone.

**Comment by nvie** [comment]
Yeah, pip-review and pip-dump where more directly acting on the installed env, which is less reliable, and therefore more likely to give different results on different machines. The pip-compile and pip-sync scripts have been created as a better alternative to the problem of pinning your dependencies, by making ("compiling") the list which is a declaration that the env should obey to, and pip-sync makes it so by installing/uninstalling all packages so the env matches the prescription.

I do realize taking away pip-review has caused some pain with people that liked it, but I believe it's for the better. Onwards and upwards :)

**Comment by jgonggrijp** [comment]
For completeness, pip-review now lives on as a separate package. Just `pip install pip-review` if you want the old program back. The repo is under my account.

**Comment by kengruven** [comment]
I don't mean to be a pain here, but I'm curious how this works.  Is it no longer possible with pip-tools to answer the question "Are there new versions of the libraries I'm using?"?

The pip-compile/pip-sync tools are great, but pip-review seemed like the Python version of "apt-get update && apt-get upgrade", and that's missing now.  (Except in a separate project -- thanks, @jgonggrijp!)

I pin all my dependencies, so I have a requirements.in which looks like:

    Foo==1.2.3

and then I pip-compile that into requirements.txt which looks like:

    Foo==1.2.3
    Bar==1.1.1  # via Foo

and that's great, but I don't see any easy way to tell what's new upstream.  When Foo 1.2.4 (or 1.3.0, or 2.0.0) is released, how can I find out about it?

With pip-compile, "--dry-run" will print to stdout, but it prints every dependency in the list, not just a summary of the ones that have upgrades.  And "--upgrade" tries to "upgrade all dependencies to their latest versions", but only their latest versions listed in the requirements.in file, so it won't tell me when a new version is released, anyway.

Once you've pinned your versions in requirements.in, how do you find upgrades?  Do you regularly go through them all by hand?  What's the intended workflow here?

thanks,

**Comment by piotr-dobrogost** [comment]
@kengruven 
See this pip issue – [Allow `pip list --outdated` to take a requirements file](https://github.com/pypa/pip/issues/3314)

**Comment by jgonggrijp** [comment]
@kengruven The intended usage is to not pin the versions in `requirements.in`. You are supposed to let `pip-compile` pin the versions for you. If you pass the `--upgrade` flag, it pins the latest version rather than the currently installed one.

The added convenience of `pip-review` is that you can try (review) the upgrades without pinning the new versions in advance. However, strictly speaking you can live with just `pip-compile` and `pip-sync`.
