### ISSUE TITLE
"Short" version number conflict

### ISSUE THREAD

**Issue by si14** [nvie/pip-tools#323]
There is a library called `django-cache-manager` which [states](https://github.com/vijaykatam/django-cache-manager/blob/d003ee9cb9fba271e50cacb0b79dd217bedb6b34/setup.py#L9-L11) `Django<=1.9`  dependency (which makes some sense). However, when trying to `pip-compile` `requirements.in` similar to 

```
...
Django==1.9.2
django-cache-manager==0.4
...
```

`pip-compile` errors out with

```
Could not find a version that matches Django<=1.9,==1.9.2,>=1.4.2,>=1.7
```

I can see how `1.9.3` may be incompatible with `<=1.9` requirement, but IMO it makes sense to assume semantic versioning and ignore minor versions. What do you think?

**Comment by nvie** [comment]
The requirement of `<=` is weird, and non-standard. Mathematically speaking, 1.9 is included in that range, but 1.9.1 is not. This is almost never the intention. So they likely either mean to say `< 1.9` (if only 1.8.x should be supported) or `< 2` (if 1.9.x must be supported). Pip-tools just follows the spec. The place to fix this is inside this package itself, not in pip-tools or pip.

**Comment by si14** [comment]
Thanks for the clarification!

**Comment by blueyed** [comment]
What I understood from the original issue was that `1.9` should be considered to be equal to `1.9.23`, and that you would use `1.9.0` to refer to that.  But then "1.9.0" might not exist, but only `1.9`.

"semver magic"?!
