### ISSUE TITLE
Trusted host option

### ISSUE THREAD

**Issue by hugoboos** [nvie/pip-tools#338]
The `--trusted-host` option in the `requirements.in` file is not copied to the `requirements.txt` file.

**Comment by antinescience** [comment]
Replicated with latest (1.6.5), for what it's worth.

**Comment by hugoboos** [comment]
Possible fix in #371

**Comment by triplepoint** [comment]
A near as I can tell, --trusted-host is no longer a supported feature _inside_ a requirements.txt file.  It's still allowed as a command line parameter and a pip.conf value.

This seems to allude to the change, but I couldn't find direct documentation of it being changed in pip:
https://github.com/pypa/pip/issues/2822

**Comment by nvie** [comment]
This is already fixed in #371, closing this now. Thanks!
