### ISSUE TITLE
Pip-compile not upgrading

### ISSUE THREAD

**Issue by Koed00** [nvie/pip-tools#342]
Since the latest version, pip-compile doesn't update the package versions in an existing requirements.txt unless specifically asked to with the `--upgrade` option.

Not sure if this is expected behaviour , because the docs and even the requirements.txt file itself do not mention using the upgrade option.

OSX 10.11.4, Python 3.5.1, pip-compile version 1.6.1

**Comment by nvie** [comment]
This is indeed the expected behaviour. I've just updated the README file to reflect this a little better. Thanks!
