### ISSUE TITLE
uninstalls packages installed with conda

### ISSUE THREAD

**Issue by FlxVctr** [nvie/pip-tools#387]
##### Steps to replicate

0. If not installed, install miniconda: http://conda.pydata.org/docs/install/quick.html#linux-miniconda-install
1. `conda create -n test pip pandas`
2. `source activate test`
3. `pip install pip-tools`
4. `touch requirements.in`
5. `pip-compile requirements.in`
6. `pip-sync`

##### Expected result

No changes as I expect it to have only an impact on packages installed with pip, i.e. returned by pip list.

##### Actual result

```
Uninstalling numpy-1.11.1:
  Successfully uninstalled numpy-1.11.1
Uninstalling pandas-0.18.1:
  Successfully uninstalled pandas-0.18.1
Uninstalling python-dateutil-2.5.3:
  Successfully uninstalled python-dateutil-2.5.3
DEPRECATION: Uninstalling a distutils installed project (pytz) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
Uninstalling pytz-2016.6.1:
  Successfully uninstalled pytz-2016.6.1
```

**Comment by nvie** [comment]
You should probably just include those packages in your requirements.in. Conda will likely install these for you automatically in the env it creates (but I'm not sure, I don't know it). If you run pip-sync, it checks which packages are in the env and which are defined in requirements.txt, and synchronizes them. pip cannot see that these packages were installed by Conda, so pip-sync can't either.

What's in `requirements.txt` and what is the output of `pip freeze` before you run the `pip-sync` step?

**Comment by FlxVctr** [comment]
`requirements.txt` ist empty and `pip freeze` returns the packages installed by conda. So yeah, I'm just using pip-tools for a not intended purpose I guess. Will try to find a workflow that turns out to do what I want. Not really the job of pip-tools I guess.
