### ISSUE TITLE
Patch versions?

### ISSUE THREAD

**Issue by alairock** [nvie/pip-tools#401]
Is there a way to generate pinned versions in the requirements.txt that allows Patch updates?

**Comment by nvie** [comment]
Yeah, you can use pip's syntax like this for that:

    django~=1.10.0   # read as "1.10.x"

Which technically translates to:

    django>=1.10.0,<1.11

If you would use:

    django~=1.10   # read as "1.x"

Then it would translate to:

    django>=1.0,<2.0

**Comment by alairock** [comment]
And that is what I put in the `requirements.in` right?

**Comment by nvie** [comment]
Yep. And then you re-run `pip-compile --upgrade requirements.in` as often as you like.

**Comment by alairock** [comment]
Ah. Not quite what I am looking for. Our CI runs `pip install -U -r requirements.txt` and we like to have patch versions auto upgrade with that. So the `.txt` version would have to be pinned to the minor versions only.

**Comment by nvie** [comment]
> So the .txt version would have to be pinned to the minor versions only.

Sorry, that's not the goal of pip-compile and is not supported. Either you'll have to update the *.txt, or pip install directly from the *.in file in your CI env.
