### ISSUE TITLE
pip-compile doesn't seem to support subpackages

### ISSUE THREAD

**Issue by Gastove** [nvie/pip-tools#404]
Working with [Airflow](http://pythonhosted.org/airflow/installation.html), which uses subpackages, e.g. `pip install airflow[s3, postgres]`. I cannot seem to find a cannon way to work around this with pip-tools, so far.
##### Steps to replicate
1. Create a new virtualenv
2. Install pip-tools
3. Create a `requirements.in` containing only the line `airflow[s3, postgres]`
4. `pip-compile requirements.in`
##### Expected result

At a minimum, the compiled `requirements.txt` should pass the subpackages along to the pinned line, e.g.:

`airflow[s3, postgres]==1.7.1.3`

In my most favorite world, this would also pin the expanded deps of those submodules (at least boto and psycopg2 in this example). 
##### Actual result

Subpackages are omitted entirely, e.g.:

`airflow==1.7.1.3`

And so are their deps.

**Comment by Gastove** [comment]
This is probably a less articulate version of #408.

**Comment by nvie** [comment]
This should be fixed by #410 and be supported from pip-tools 1.8 onwards, which will be released shortly.

**Comment by Gastove** [comment]
Brilliant, thanks!
