### ISSUE TITLE
Extras not propagated into requirements.txt after insertion

### ISSUE THREAD

**Issue by coriolinus** [nvie/pip-tools#408]
Extras, in this context, are specific functional extensions to a particular package.

This is similar to #154 but differs because this triggers when adding an extra to an existing requirement.

The cached result appears to prevent appropriate detection that the extra was added.

##### Steps to replicate

1. Create a `requirements.in` as follows:
  ```text
pip-tools
hypothesis
   ```
2. Run `pip-compile` from the command line.
3. Edit the requirements.in file to the following:
  ```text
pip-tools
hypothesis[django]
  ```
4. Re-run `pip-compile` from the command line.
3. Examine `requirements.txt`

##### Expected result

```text
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file reqs.txt reqs.in
#
click==6.6                # via pip-tools
django==1.10.3            # via hypothesis
fake-factory==0.7.2       # via hypothesis
first==2.0.1              # via pip-tools
hypothesis[django]==3.6.0
pip-tools==1.7.0
python-dateutil==2.6.0    # via fake-factory
pytz==2016.7              # via hypothesis
six==1.10.0               # via fake-factory, pip-tools, python-dateutil
```

##### Actual result

```text
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file reqs.txt reqs.in
#
click==6.6                # via pip-tools
first==2.0.1              # via pip-tools
hypothesis==3.6.0
pip-tools==1.7.0
six==1.10.0               # via pip-tools
```

##### Workaround

Simply deleting the existing `requirements.txt` file and installing from scratch appears to work, but shouldn't be a necessary part of the pip-tools workflow.

**Comment by nvie** [comment]
This is now fixed via #410 and will be part of pip-tools 1.8.  Thanks for the fantastic report, @coriolinus!
