### ISSUE TITLE
add --no-cache option to pip-compile

### ISSUE THREAD

**Issue by mlfz** [nvie/pip-tools#436]
A rehash of closed issue #17.

In our CI build script, we use `pip-compile` to ensure python requirements consistency.  Our `requirements.in` has `-e git+ssh://github/...` dependencies.  As a result, `pip-compile` checks out the repositories and building up `.cache/pip-tools`:
```
build-xenial-01:/home/jenkins$ sudo du -h .cache/pip-tools
120M	.cache/pip-tools/wheels
75G	.cache/pip-tools/pkgs
75G	.cache/pip-tools
```
which eventually fills up `/home/`.  Please implement an option for not using cache or clearing cache.

**Comment by davidovich** [comment]
@mlfz Clearing the cache is already possible: 

`pip-compile --rebuild`

or 

`pip-compile -r`

**Comment by mlfz** [comment]
Thanks! My apology.
