### ISSUE TITLE
Migrate dependency management

### ISSUE THREAD

**Issue by emilecaron** [nvie/pip-tools#442]
should consider replacing pip-tools with https://github.com/kennethreitz/pipenv

- [ ] Migrate current functionalities to new tool
- [ ] Investigate virtualenv features
- [ ] Investigate dev environment features

**Comment by emilecaron** [comment]
woops. wrong repo. sry.

**Comment by anthrotype** [comment]
Don't be sorry. Thanks to you I discovered that cool new project! ;)
